In [2]:
matrix = [[1, 2, 3],
[4, 5, 6],
[7, 8, 9]]

In [3]:
[[i + 1 for i in row] for row in matrix]

[[2, 3, 4], [5, 6, 7], [8, 9, 10]]

In [1]:
import numpy as np

In [2]:
array1 = np.array([10, 1000, 1000.])

In [4]:
array2 = np.array([[1.,2.,3.],[4.,5.,6.]])

In [5]:
array1.dtype

dtype('float64')

In [6]:
array2 + 1

array([[2., 3., 4.],
       [5., 6., 7.]])

In [7]:
array2 * array2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [8]:
array2 * array1

array([[  10., 2000., 3000.],
       [  40., 5000., 6000.]])